services:
  never-stelle:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: never-stelle
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./media:/media
      - ./scratch:/scratch
    ports:
      - "8088:8088"
