services:
  never-stelle:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: never-stelle
    restart: unless-stopped
    environment:
      APP_DATA_DIR: /app/data
      FRONTEND_DIR: /app/frontend
      ACCESSIBLE_VOLUMES_ROOTS: /library|/media
    volumes:
      - ./data:/app/data
      - ./library:/library
    ports:
      - "8088:8088"
